char* cat_string(char* l, char* r);
char* get_string_ref(char* str);
char* itos(int a);
char* get_file_name(char* file_addres);
char* get_file_type(char* file_addres);
char* get_date(int date);
char* replace_name_with_hash(char* file_addres);
int is_directory(char *path);
int is_file(char *path);
int stoi(char* s);
char* get_hash(char* s);